version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: vehicle-tracker-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-vehicle_tracker_dev}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./server/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-vehicle_tracker_dev}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    tmpfs:
      - /tmp
      - /var/run/postgresql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Backend API (Development)
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    container_name: vehicle-tracker-api-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-vehicle_tracker_dev}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      JWT_SECRET: ${JWT_SECRET:-dev-jwt-secret-key}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-24h}
      UPLOAD_DIR: /app/uploads
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-10485760}
      CORS_ORIGIN: http://localhost:3000
      TZ: ${TZ:-UTC}
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    volumes:
      - ./server:/app:rw
      - /app/node_modules
      - uploads_dev_data:/app/uploads:rw
      - logs_dev_data:/app/logs:rw
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    command: npm run dev
    tmpfs:
      - /tmp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Frontend (Development)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
      args:
        NODE_ENV: development
    container_name: vehicle-tracker-frontend-dev
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
      TZ: ${TZ:-UTC}
    volumes:
      - ./client:/app:rw
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api
    command: npm start
    tmpfs:
      - /tmp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_dev_data:
    driver: local
  uploads_dev_data:
    driver: local
  logs_dev_data:
    driver: local

networks:
  default:
    name: vehicle-tracker-dev-network
    driver: bridge